spring:
  application:
    name: banking-practice
  datasource:
    url: jdbc:postgresql://localhost:5432/banking-practice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: BankingPractice
      # Công thức: connections = (core_count * 2) + effective_spindle_count
      # Máy 4 core, SSD → 4*2+1 = 9, làm tròn lên 10
      maximum-pool-size: 10
      minimum-idle: 3
      # Fail fast: 3s thay vì default 30s
      connection-timeout: 3000
      idle-timeout: 600000      # 10 phút
      max-lifetime: 1800000     # 30 phút
      connection-test-query: SELECT 1
  flyway:
    enabled: true  # Enable Flyway cho PostgreSQL
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      # Serialize message thành JSON
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      # acks=all → đợi tất cả replica xác nhận trước khi coi là gửi thành công
      # Quan trọng trong banking — không để mất message
      acks: all

      # Thử lại tối đa 3 lần nếu gửi thất bại
      retries: 3

      properties:
        # Đảm bảo không gửi duplicate khi retry
        enable.idempotence: true

    consumer:
      group-id: banking-service
      auto-offset-reset: earliest   # Đọc từ đầu nếu chưa có offset
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # Chỉ trust class trong package này, tránh deserialization attack
        spring.json.trusted.packages: "com.cuongpq.bankingpractice.event"

    # Dead Letter Queue — message lỗi sau 3 lần retry sẽ vào đây
    listener:
      ack-mode: MANUAL_IMMEDIATE    # Tự tay ack, không auto

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics, info
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: banking-api   # label xuất hiện trên mọi metric
    distribution:
      percentiles-histogram:
        http.server.requests: true   # bật histogram để tính P99
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
# ==================== LOGGING ====================
#logging:
#  level:
#    root: INFO
#    com.cuongpq.bankingpractice: DEBUG
#    org.springframework.web: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"